### ISSUE TITLE
not working on L10

### ISSUE THREAD

**Issue by Saifallak** [mantas-done/laravel-apm#4]
installed the package and the screen is always empty
![image](https://github.com/mantas-done/laravel-apm/assets/6053156/ad4456b3-5ae4-43e8-826d-04cd3f3bc366)

**Comment by Saifallak** [comment]
anyway to run tests on this?

**Comment by Saifallak** [comment]
there is no files created at `storage/app/apm` even folder wasnt created.

**Comment by mantas-done** [comment]
Hi, most likely you haven't added APM=1 to your .env file. Have this fixed your issue?
