### ISSUE TITLE
in_array(): Argument #2 ($haystack) must be of type array, null given

### ISSUE THREAD

**Issue by RayWP** [mantas-done/laravel-apm#6]
Laravel Version: 9.52.16
PHP Version: 8.2.4
OS: Windows 11

Context:
I followed the tutorial [here](https://medium.com/@mantasd/laravel-apm-performance-monitor-b0dad8e9fd13), at first I can open the dashboard. After the .txt log starts filling, i received error as below:
![image](https://github.com/mantas-done/laravel-apm/assets/54213470/3d644c56-fc06-4ced-99de-88a0ae7c2921)

Shall we discuss together on how to solve this?
Thank you! :D

**Comment by mantas-done** [comment]
Hi, can you open "vendor frames" tab and check which file throws the
exception?
Also, what version of apm is installed?
